hello_w: hello_w.c
	cc -g -Wall -Wextra hello_w.c -o hello_w -pthread

.PHONY: clean	
clean:
	rm -f hello_w
	
#rules
#target: dependencias
#[tab]command
#make
# make clean
# ./hello_w >> jiji.txt : usar eso como salida sin sobrescribir
# ./hello_w > jiji.txt : usar como salida estandar SOBRESCRIBIENDO
#
#
